export const courses = [
    { value: 1, name: "Ciências Biológicas" },
    { value: 7, name: "Física" },
    { value: 8, name: "Química" },
    { value: 9, name: "Geografia" },
    { value: 10, name: "História" },
    { value: 11, name: "Filosofia" },
    { value: 12, name: "Psicologia" },
    { value: 13, name: "Arquitetura" },
    { value: 14, name: "Engenharia Elétrica" },
    { value: 15, name: "Administração" },
    { value: 16, name: "Economia" },
    { value: 17, name: "Direito" },
    { value: 18, name: "Odontologia" },
    { value: 19, name: "Enfermagem" },
    { value: 20, name: "Farmácia" },
    { value: 21, name: "Nutrição" },
    { value: 22, name: "Educação Física" },
    { value: 23, name: "Ciência da Computação" },
    { value: 24, name: "Engenharia de Produção" },
    { value: 25, name: "Artes Visuais" },
    { value: 26, name: "Música" },
    { value: 27, name: "Design" },
    { value: 28, name: "Jornalismo" },
    { value: 29, name: "Publicidade e Propaganda" },
    { value: 30, name: "Relações Internacionais" },
    { value: 31, name: "Engenharia Mecânica" },
    { value: 32, name: "Engenharia Química" },
    { value: 33, name: "Engenharia de Alimentos" },
    { value: 34, name: "Engenharia de Telecomunicações" },
    { value: 35, name: "Engenharia Ambiental" },
    { value: 36, name: "Engenharia de Controle e Automação" },
    { value: 37, name: "Engenharia de Computação" },
    { value: 38, name: "Engenharia de Materiais" },
    { value: 39, name: "Engenharia Civil" },
    { value: 40, name: "Engenharia de Minas" },
    // Add more courses representing different areas of knowledge
];
