export const TESTE_LOGIN = {
  matricula: 304040,
  curso: "Engenharia de Computação",
  email: "oi@ufrgs.br",
  genero: "Masculino ",
  tipoDeUser: "Locador",
  minhasNotificacoes: [
    {
      LocatarioID: 304040,
      State: "Aprovado",
      Room: {
        id: 1,
        titulo: "Quarto 1",
        descricao: "Quarto 1",
        preco: 1000,
        localizacao: "Rua 1",
        numeroQuartos: 5,
        campusProximo: "Campus do Vale",
        owner: {
          matricula: 374040,
          curso: "Engenharia da Computação",
          email: "oi2@ufrgs.br",
          genero: "Masculino Cisgênero",
        },
      },
    },
  ],
};
